microsoft/ApplicationInsights-aspnetcore

- src/Microsoft.ApplicationInsights.AspNet/ExceptionTrackingMiddleware.cs
- src/Microsoft.ApplicationInsights.AspNet/Extensions/ApplicationInsightsExtensions.cs
- src/Microsoft.ApplicationInsights.AspNet/RequestTrackingMiddleware.cs
To address issue #22, this change removes term "ApplicationInsights" from the names of our middleware classes because it already appears in the namespace. It also adds term "Tracking" to make middleware class names more descriptive.
> Make names of middleware classes shorter and more descriptive

- src/Microsoft.ApplicationInsights.AspNet/project.json
ASP.NET runtime packages dropped build number from packages version and our package will not work with the default Visual Studio RC installation. I propose to release a hotfix today that only changes references. Going forward we can try to drop MyGet from the list of NuGet sources completely.
> change references to point to RC packages

- ApplicationInsights.AspNet.sln
- test/StartupPerf/startupPerf.ps1
I run it many times - typically times very similar. Worst I get out of two sequential runs is 0.4 sec:
```
with AI	without AI	
6903.4364	5701.4235	
6285.2875	5988.7779	
6400.6323	5757.9383	
6109.9152	6126.5687	
6283.0474	5906.7686	
6237.337	5944.2693	
6199.4625	6948.1886	
6467.1623	5916.281	
7070.9624	5805.3368	
6397.2912	5813.8167	overhead:
avg:	6435.45342	5990.93694	444.51648
```
> measure startup time under debugger in Visual studio

- ApplicationInsights.AspNet.sln
- Common.targets
- src/Microsoft.ApplicationInsights.AspNet/Microsoft.ApplicationInsights.AspNet.xproj
- test/FunctionalTestUtils/FunctionalTestUtils.xproj
- test/Microsoft.ApplicationInsights.AspNet.Tests/Microsoft.ApplicationInsights.AspNet.Tests.xproj
- test/Mvc6Framework45.FunctionalTests/Mvc6Framework45.FunctionalTests.xproj
- test/Mvc6Framework45.FunctionalTests/package.json
- test/Mvc6Framework45.FunctionalTests/project.json
- test/WebApiShimFw46.FunctionalTests/WebApiShimFw46.FunctionalTests.xproj
`msbuild ApplicationInsights.AspNet.sln` fails out of the box with Visual Studio 2015 RC when any of the NuGet packages are missing from the .dnx/packages cache. This pull request adds a custom MSBuild .targets file that executes `dnu` to restore the packages. 
This pull request also adds all build-time NPM dependencies to package.json, including Bower and Gulp, to enable their automatic installation on the CI server during build.
> Enable automated CI build of ApplicaitonInsights.AspNet.sln

- NuGet.config
- src/Microsoft.ApplicationInsights.AspNet/project.json
update NuGet.conf to not point to unreachable repository, and update dependencies in project.json to latest beta5, instead of oldest beta5.  Applies to Microsoft/ApplicationInsights-aspnet5#84
> Fix dependencies so fresh builds will work out-of-the box

- RunTests.ps1
- test/Mvc6Framework45.FunctionalTests/FunctionalTest/ExceptionTelemetryTests.cs
- test/Mvc6Framework45.FunctionalTests/Startup.cs
- Use test project directory as the current working directory during
execution.
- Figured out issue#91 and updated test expectation for the failing test
for now.
- ASP.Net Error handling middleware logs failed requests as Error and
the ConsoleLogger ends up writing it to powershell resulting in CI
failing. Moved ConsoleLogger to only Development environment.
> Fix unit tests in CI

- ApplicationInsights.AspNet.sln
- src/Microsoft.ApplicationInsights.AspNet/TelemetryInitializers/OperationNameTelemetryInitializer.cs
- test/EmptyApp.FunctionalTests/EmptyApp.FunctionalTests.xproj
- test/EmptyApp.FunctionalTests/FunctionalTest/ExceptionTelemetryTests.cs
- test/EmptyApp.FunctionalTests/FunctionalTest/RequestTelemetryTests.cs
- test/EmptyApp.FunctionalTests/Startup.cs
- test/EmptyApp.FunctionalTests/hosting.ini
- test/EmptyApp.FunctionalTests/project.json
- test/FunctionalTestUtils/project.json
- test/Microsoft.ApplicationInsights.AspNet.Tests/TelemetryInitializers/OperationNameTelemetryInitializerTests.cs
Fixing https://github.com/Microsoft/ApplicationInsights-aspnet5/issues/112
> allow monitoring of non-MVC apps

- global.json
- src/Microsoft.ApplicationInsights.AspNet/Extensions/ApplicationInsightsExtensions.cs
- src/Microsoft.ApplicationInsights.AspNet/project.json
- test/EmptyApp.FunctionalTests/Startup.cs
- test/EmptyApp.FunctionalTests/project.json
- test/FunctionalTestUtils/project.json
- test/Microsoft.ApplicationInsights.AspNet.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
- test/Microsoft.ApplicationInsights.AspNet.Tests/project.json
- test/Mvc6Framework45.FunctionalTests/Startup.cs
- test/Mvc6Framework45.FunctionalTests/project.json
- test/WebApiShimFw46.FunctionalTests/Startup.cs
- test/WebApiShimFw46.FunctionalTests/project.json
Adding server telemetry channel, enabling sampling (with default adaptive) and removing existing configure option to create config.
- TelemetryConfiguration.Active is used if services do not have an existing configuration instance, in which case it picks the configuration from the services and updates it.
- Server telemetry channel is assigned to `config.TelemetryChannel` only in full framework, and if no other telemetry channel exists in services (in which case, `config.TelemetryChannel` will be the existing channel in services).
- Neither the channel nor the sampling processor is added to the services collection. 
- Customers have access to telemetry configuration, and can add his own custom telemetry processors through chain builder. 
- Customers can disable sampling using the …
> Adding server telemetry channel, adaptive sampling and making Active as default configuraiton.

- src/Microsoft.ApplicationInsights.AspNet/Extensions/ApplicationInsightsExtensions.cs
- src/Microsoft.ApplicationInsights.AspNet/Extensions/ApplicationInsightsServiceOptions.cs
- test/Microsoft.ApplicationInsights.AspNet.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
EnableAdaptiveSampling is by default true and overriding it with false will not enable the sampling feature.
> Change DisableDefaultSampling to EnableAdaptiveSampling

- RunTestsCore.ps1
- build.ps1
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsServiceOptions.cs
- test/EmptyApp.FunctionalTests/project.json
- test/FunctionalTestUtils/BackTelemetryChannel.cs
- test/FunctionalTestUtils/InProcessServer.cs
- test/FunctionalTestUtils/TelemetryTestsBase.cs
- test/FunctionalTestUtils/project.json
- test/MVCFramework45.FunctionalTests/MVCFramework45.FunctionalTests.xproj
- test/MVCFramework45.FunctionalTests/project.json
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/TelemetryInitializers/ComponentVersionTelemetryInitializerTests.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/project.json
- test/WebApiShimFw46.FunctionalTests/project.json
- Quick pulse metric stream is now enabled by default, and is the first telemetry processor. Default addition can be controlled using service option: ```EnableQuickPulseMetricStream```
- Fixing minor dependency warnings in functional tests that are causing build to fail.
> Enabling quickpulse metric stream by default along with the associated service option

- NuGet.config
- Signing.props
- dirs.proj
- src/Microsoft.ApplicationInsights.AspNetCore/project.json
Updated dirs.proj to build target only the core library.
Added DownloadFile and ExtractZipArchive tasks.
Added FilesToSign and Signing.props and output messages.
Added Clean, CheckBuildParameters, DownloadCLI, AfterBuild, and PackageNuGet Targets .
Added dotnet CLI zip file download and extract and switched to dotnet build from msbuild.
> Updated dirs.proj to build target only the core library.

- src/Microsoft.ApplicationInsights.AspNetCore/Resources.Designer.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Resources.resx
This updates the JS snippet from the latest in the ApplicationInsights-JS repo. I've left in the minor differences of course like the {0} for the inst key and CDN path.
See Microsoft/ApplicationInsights-JS#295 for additional context.
> Update JS snippet from the ApplicationInsights-JS repo

- CHANGELOG.md
- SetEnv.targets
- src/Microsoft.ApplicationInsights.AspNetCore/project.json
- test/EmptyApp.FunctionalTests/project.json
- test/FunctionalTestUtils/project.json
- test/MVCFramework45.FunctionalTests/project.json
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/project.json
- test/WebApiShimFw46.FunctionalTests/project.json
Should fix [https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/272](https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/272)
> Marked the analyzers for build only and not NuGet packaging.  Rev'ed versioning.

- dirs.proj
- src/Microsoft.ApplicationInsights.AspNetCore/project.json
- test/FunctionalTestUtils/TelemetryTestsBase.cs
Removed utils project from list of projects to run dotnet test on.
Updated the version of AI SDK's referenced.
Replaced the InRange test with a custom implementation.
Got test start time from the stopwatch instead of DateTimeOffset.Now which is less accurate.
> Fixed intermittent test failures and updated package references.

- test/FunctionalTestUtils/TelemetryTestsBase.cs
- test/WebApiShimFw46.FunctionalTests/project.json
- test/WebApiShimFw46.FunctionalTests/xunit.runner.json
Added xunit runner config file to prevent test parallelization.
Changed formatting, cleared the buffer and checked for the right named object, and added locking.
Subtracted 50 milliseconds from the test start time to compensate for the build lab reporting earlier timestamps for telemetry items.
> Trying to prevent the weird test timing issues.

- src/Microsoft.ApplicationInsights.AspNetCore/ApplicationInsightsJavaScript.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsServiceOptions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Implementation/ApplicationInsightsInitializer.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLoggerFactoryExtensions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/DebugLoggerControl.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Resources.Designer.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Resources.resx
- src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/AspNetCoreEnvironmentTelemetryInitializer.cs
- src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/WebSessionTelemetryInitializer.cs
- src/Microsoft.ApplicationInsights.AspNetCore/project.json
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/JavaScript/ApplicationInsightsJavaScriptTest.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/TelemetryInitializers/AspNetCoreEnvironmentTelemetryInitializerTests.cs
Add AspNetCore environment initializer. Fixes: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/312
Authenticated user tracking script support. Fixes: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/311
Do not output client javascript if telemetry is disabled. Fixes: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/313
Prevent debug logging if instrumentation key exists. Fixes: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/314
Disable debug logger if other loggers are being added to ILoggerFactory. Fixes: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/315
@SergeyKanzhelev @dnduffy
> Fix couple 2.0-beta issues

- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs
- src/Microsoft.ApplicationInsights.AspNetCore/project.json
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/RequestTrackingMiddlewareTest.cs
Also upgrades references to 2.3.0-beta3.
Takes advantage of the overloads of Start/Stop that were added for https://github.com/Microsoft/ApplicationInsights-dotnet/pull/424
> Use accurate timestamps in HostingDiagnosticListener

- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
Mostly fixing a repeated typo of "instance", but normalized the other XML docs while here.
> Typo and consistency fixes for ApplicationInsightsExtensions

- src/Microsoft.ApplicationInsights.AspNetCore/Implementation/ApplicationInsightsInitializer.cs
- test/FunctionalTestUtils/BackTelemetryChannel.cs
- test/MVCFramework45.FunctionalTests/FunctionalTest/DependencyTelemetryMvcTests.cs
1. OperationIdOfRequestIsPropagatedToChildDependency:
- was failing because CorrelationIdLookupHelper was not set up properly and test was checking internal AI trace message instead on dependency telemetry
- was failing because there are 2 dependencies: one is call to application from the test, another one was reported in the controller
2. TestBasicDependencyPropertiesAfterRequestingBasicPage 
was failing because AI was not disposed properly and magically application was using old telemetry channel remaining from the previous test and test was checking new telemetry channel.
While the magic that kept TelemetryChannel alive is still unknown, AI is now properly disposed and test is fixed.
> Fix OperationIdOfRequestIsPropagatedToChildDependency and TestBasicDependencyPropertiesAfterRequestingBasicPage functional tests

- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
- test/EmptyApp.FunctionalTests/FunctionalTest/RequestTelemetryEmptyAppTests.cs
- test/EmptyApp.FunctionalTests/FunctionalTest/TelemetryModuleWorkingEmptyAppTests.cs
- test/FunctionalTestUtils/BackTelemetryChannel.cs
- test/FunctionalTestUtils/TelemetryTestsBase.cs
- test/MVCFramework45.FunctionalTests/FunctionalTest/DependencyTelemetryMvcTests.cs
- test/MVCFramework45.FunctionalTests/FunctionalTest/RequestTelemetryMvcTests.cs
- test/MVCFramework45.FunctionalTests/FunctionalTest/TelemetryModuleWorkingMvcTests.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
- test/WebApiShimFw46.FunctionalTests/FunctionalTest/TelemetryModuleWorkingWebApiTests.cs
Enable dependency collector for .Net core framework and also fix unit tests
> Enable dependency collector for .Net core framework

- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
- test/MVCFramework45.FunctionalTests/FunctionalTest/CorrelationMvcTests.cs
- test/MVCFramework45.FunctionalTests/FunctionalTest/DependencyTelemetryMvcTests.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
Add some domains as a temporary workaround. Will probably be configurable when the configuration story is clear.
> Fix issue #416. Add certain domains to dependency collector's exclude list

- src/Microsoft.ApplicationInsights.AspNetCore/project.json
We see downgrade warnings during asp.net core build process. This PR aligns version of `System.Net.NameResolution` with one used by other packages from `NETStandard.Library 1.6.1` 
```
Detected package downgrade: System.Net.NameResolution from 4.3.0 to 4.0.0  [C:\b\w\590aeb6bc9b87cb8\.r\AzureIntegration\.build\KoreBuild.proj]
ApplicationInsightsHostingStartupSample (>= 1.0.0) -> Microsoft.AspNetCore.ApplicationInsights.HostingStartup (>= 2.0.0-preview1-24822) -> Microsoft.ApplicationInsights.AspNetCore (>= 2.1.0-beta2) -> NETStandard.Library (>= 1.6.1) -> System.Net.Sockets (>= 4.3.0) -> runtime.unix.System.Net.Sockets (>= 4.3.0) -> System.Net.NameResolution (>= 4.3.0)  [C:\b\w\590aeb6bc9b87cb8\.r\AzureIntegration\.build\KoreBuild.proj]
ApplicationInsightsHostingStartupSample (>= 1.0.0) …
```
> Align System.Net.NameResolution with NETStandard.Library

- src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptionsSetup.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/FakeTelemetryProcessor.cs
This is necessary to complete exception snapshotting work for .NET Core and overall a good addition, filling a gap in programmatic initialization capabilities of AI SDK.
> Ability to add telemetry processors through DI

- src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptionsSetup.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/FakeTelemetryProcessor.cs
This change is required to unblock exception snapshotting on .NET Core, for more info see issue https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/447
> Telemetry processors are initialized if they implement ITelemetryModule

- test/EmptyApp.FunctionalTests/FunctionalTest/RequestTelemetryEmptyAppTests.cs
- test/FunctionalTestUtils/TelemetryTestsBase.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/RequestTrackingMiddlewareTest.cs
Removed obsolete HttpMethod property references that were throwing exceptions looking up an unused key in the RequestTelemetry internal dictionary.
> Fixed key not present error.

- src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLogger.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Logging/ApplicationInsightsLoggerTests.cs
Tracking `ExceptionTelemetry` instances rather than `TraceTelemetry` provides a nicer experience in UI's such as Visual Studio and the Azure portal.
Resolves #393
> Use ExceptionTelemetry for tracking exceptions

- src/Microsoft.ApplicationInsights.AspNetCore/Implementation/ProviderAliasAttribute.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLoggerFactoryExtensions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLoggerProvider.cs
In logging 2.0 we added ability to configure logging filters in centralized way. To configure filters per logging provider provider full name should be used or alternatively alias specified by `ProviderAliasAttribute`.
`ProviderAliasAttribute` is late bound and is detected by full type name so no reference to new aspnetcore packages is required.
@dnduffy @SergeyKanzhelev
> Add alias to AI logger provider

- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/MvcDiagnosticsListener.cs
- src/Microsoft.ApplicationInsights.AspNetCore/ITelemetryProcessorFactory.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptionsSetup.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/TelemetryInitializers/OperationNameTelemetryInitializerTests.cs
Instead of injecting `Func<,>` factory interface is introduced.
OperationName from MVC Razor Page is generated the same way controller/action is makes for simpler code change and consistent behavior.
https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/482
https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/430
@dnduffy
> Fix Func injection issue on structuremap and track MVC page names

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/project.json
- test/FunctionalTestUtils/InProcessServer.cs
> Fix issue 488.

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/TelemetryInitializerBase.cs
To prevent HTTP context corruption
> Synchronize HTTP context access

- dirs.proj
Build definition modified to build tests all the time. The flag runtests only determine whether the tests are run or not.
This is required to split the build and test steps into separate tasks in build lab,
> Build definition modified to build tests all the time. 

- CHANGELOG.md
- dirs.proj
- src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj
- test/MVCFramework45.FunctionalTests/FunctionalTest/DependencyTelemetryMvcTests.cs
- test/MVCFramework45.FunctionalTests/FunctionalTest/ExceptionTelemetryMvcTests.cs
- test/MVCFramework45.FunctionalTests/FunctionalTest/RequestTelemetryMvcTests.cs
- test/MVCFramework45.FunctionalTests/FunctionalTest/TelemetryModuleWorkingMvcTests.cs
- test/WebApiShimFw46.FunctionalTests/FunctionalTest/ExceptionTelemetryWebApiTests.cs
- test/WebApiShimFw46.FunctionalTests/FunctionalTest/RequestTelemetryWebApiTests.cs
- test/WebApiShimFw46.FunctionalTests/FunctionalTest/TelemetryModuleWorkingWebApiTests.cs
Version updated to 2.2.0-beta1
Minor renaming of tests namespaces for easier visibility in VS Test Explorer
dirs.proj - test is separated into own build target which runs after build for ease of understanding build logs.
> Version and some minor changes

- dirs.proj
- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/ContextData.cs
- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/CorrelationIdLookupHelper.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptionsSetup.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj
- src/Microsoft.ApplicationInsights.AspNetCore/SdkVersionUtils.cs
- test/EmptyApp.FunctionalTests/EmptyApp.FunctionalTests.csproj
- test/EmptyApp.FunctionalTests/FunctionalTest/TelemetryModuleWorkingEmptyAppTests.cs
- test/FunctionalTestUtils/FunctionalTestUtils.csproj
- test/FunctionalTestUtils/TelemetryTestsBase.cs
- test/MVCFramework45.FunctionalTests/FunctionalTest/CorrelationMvcTests.cs
- test/MVCFramework45.FunctionalTests/FunctionalTest/DependencyTelemetryMvcTests.cs
- test/MVCFramework45.FunctionalTests/FunctionalTest/TelemetryModuleWorkingMvcTests.cs
- test/MVCFramework45.FunctionalTests/MVCFramework45.FunctionalTests.csproj
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Microsoft.ApplicationInsights.AspNetCore.Tests.csproj
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/SdkVersionTestUtils.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/TelemetryInitializers/DomainNameRoleInstanceTelemetryInitializerTests.cs
- test/WebApiShimFw46.FunctionalTests/FunctionalTest/TelemetryModuleWorkingWebApiTests.cs
- test/WebApiShimFw46.FunctionalTests/WebApiShimFw46.FunctionalTests.csproj
Added a new target net46 for the aspnet core project, and replaced all testing to target net46 instead of net451. The motivation behind this is to run tests using stable version of xunit, which no longer support net451.
> Add net46 target to source, and replace testing with net46 instead of net451

- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryProcessorFactory.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/FakeTelemetryProcessorWithImportingConstructor.cs
We changed the way TelemetryProcessors are injected in #489 
This makes it more cumbersome for callers, since they have to define a `TelemetryProcessorFactory` class instead of just using an inline lambda.
We can help by adding a generic extension method that uses a generic telemetry processor factory.
> Add an AddApplicationInsightsTelemetryProcessor extension method

- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/CorrelationIdLookupHelper.cs
This pullrequest is to solve an issue where appId detection is incorrectly using a non-200 http response as appId and is breaking applications.
Issue: #524
> Check appId response code before using content

- src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj
Update Base and Web SDK references.
@cijothomas, can you confirm that the last two PackageReferences are needed?
They look identical to the previous two. 
They were both upgraded in the [last release](https://github.com/Microsoft/ApplicationInsights-aspnetcore/pull/540/files) so I did the same.
> update base and web references to 2.5.0-beta2

- .github/PULL_REQUEST_TEMPLATE.md
- Readme.md
- dirs.proj
- disablestrongnamevalidation.ps1
- enablestrongnamevalidation.ps1
- findMsBuild.cmd
- test/EmptyApp.FunctionalTests/EmptyApp.FunctionalTests.csproj
- test/EmptyApp20.FunctionalTests/EmptyApp20.FunctionalTests20.csproj
- test/FunctionalTestUtils/FunctionalTestUtils.csproj
- test/FunctionalTestUtils20/FunctionalTestUtils20.csproj
- test/FunctionalTestUtils20/InProcessServer.cs
- test/MVCFramework.FunctionalTests/MVCFramework.FunctionalTests.csproj
- test/MVCFramework20.FunctionalTests/MVCFramework20.FunctionalTests20.csproj
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Microsoft.ApplicationInsights.AspNetCore.Tests.csproj
- test/WebApi.FunctionalTests/WebApi.FunctionalTests.csproj
- test/WebApi20.FunctionalTests/WebApi20.FunctionalTests20.csproj
added script to disable sn check
Removed signing for test projects - this was causing tests to be not discovered by dotnet test/vstest tools for NET46 targets,
NO product code changes.
> Remove signing from test projects

- src/Microsoft.ApplicationInsights.AspNetCore/Common/InjectionGuardConstants.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Common/StringUtilities.cs
- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/CorrelationIdLookupHelper.cs
- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HeadersUtilities.cs
- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs
- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HttpHeadersUtilities.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Extensibility/Implementation/Tracing/AspNetEventSource.cs
- src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/OperationCorrelationTelemetryInitializer.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/CorrelationIdLookupHelperTest.cs
Addresses security concerns about malicious user attempting to send request with unreasonably large request headers. As SDK reads these values and stores locally/make part of Telemetry items, they can cause undesirable effects like high mem/cpu/ etc.
This attempts to enforce limits on values read from outside requests/responses.
> Enforce limits of values read from incoming headers and app id lookup

- src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/AspNetCoreEnvironmentTelemetryInitializer.cs
- src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/AzureWebAppRoleEnvironmentTelemetryInitializer.cs
- src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/ClientIpHeaderTelemetryInitializer.cs
- src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/DomainNameRoleInstanceTelemetryInitializer.cs
- src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/OperationCorrelationTelemetryInitializer.cs
- src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/OperationNameTelemetryInitializer.cs
- src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/SyntheticTelemetryInitializer.cs
- src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/TelemetryInitializerBase.cs
- src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/WebSessionTelemetryInitializer.cs
- src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/WebUserTelemetryInitializer.cs
TelemetryInitializers being internal makes it difficult to remove an individual one. (need reflection magic to achieve this currently)
Fix Issue # .
https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/351
https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/346
> Make all built-in TelemetryInitializers public to enable easy removal

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/Resources.resx
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/JavaScript/ApplicationInsightsJavaScriptTest.cs
Fix Issue # .
Serverside telemetry is not correlated with client side PageViews.
[Reported in WebSDK](https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/826)
Fixed by updating with latest snipped from [Github/ApplicationInsights-JS](https://github.com/Microsoft/ApplicationInsights-JS)
> update JS snippet with latest from github/applicationinsights-js

- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Microsoft.ApplicationInsights.AspNetCore.Tests.csproj
Enables ServerTelemetryChannel tests for both full .NET Framework and .NET Core.
Enabled NETCOREAPP2.0 for UnitTests.
Minor test tweaks.
> Test fixes for ServerTelemetryChannel

- CHANGELOG.md
- NuGet.config
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsServiceOptions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptionsSetup.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
Extension of issue Microsoft/ApplicationInsights-dotnet-server#868 "Enabling Heartbeat in App Services..." in .NET Core scenarios.
- Add EnableHeartbeat to `ApplicationInsightsServiceOptions`, reviewed with @cijothomas
> Ensure Heartbeat properties for App Services is included in AspNetCore

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/Extensibility/Implementation/Tracing/AspNetEventSource.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/ITelemetryModuleConfigurator.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptionsSetup.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryModuleConfigurator.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/FakeTelemetryProcessor.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/TestTelemetryModule.cs
More tests are needed. Submitting a PR to get early feedback before I spend too much time.
Pending: 
Document how to use this in Wiki.
Determine what to do if the Module is not found. Throw? Or just log and move on? 
Make SDK also use this extension to configure DependencyCollector.
Fix Issue # .
> Added extension method to allow configure any TelemetryModule.

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptionsSetup.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
Fixes:
https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/641
https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/642
This does not change existing behaviours:
1. ServerTelemetryChannel is added by default
2. If user adds any ITelemetryChannel to DI, then it takes precedence over default.
3. If user explicitly removed all channels, SDK falls back to base sdk provided default channel (InMemoryChannel)
How to modify channel after this PR?
Add the following in `ConfigureServices()` method of Application Startup class.
```
services.AddSingleton(typeof(ITelemetryChannel), new InMemoryChannel() {MaxTelemetryBufferCapacity = 19898 });
```
(SDK will pick this channel up automatically, and applies to TelemetryConfiguration)
This also modifies QP/Sampling enableing …
> Make channel easily configurable

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/Extensibility/Implementation/Tracing/AspNetEventSource.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptionsSetup.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
Add QuickPulseTelememodule to DI so as to enable retrieval and configuration of the same by user. 
QP is enabled by configuring it based on the user supplied flag EnableQuickPulse as before. But now users can use the extension method services.ConfigureTelemetryModule<QPModule>() to configure QP module.
Fix Issue #639 
> Make QuickPulse configurable by adding it to DI like all other modules

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsWebHostBuilderExtensions.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Microsoft.ApplicationInsights.AspNetCore.Tests.csproj
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/appsettings.json
Fix Issue #605 .
DefaultApplicationInsightsServiceConfigureOptions was not injected when using extension method AddApplicationInsightsTelemetry , which meant that ikey was not read from env/appsettings when using this extension method. This PR makes the behaviour consistent with UseApplicationInsights() extension method, which had injected DefaultApplicationInsightsServiceConfigureOptions , and hence read ikey/other settings from appsettigs.json
- Please follow [these] …
> AddApplicationInsightsTelemetry also reads ikey from appsettings.json

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/DomainNameRoleInstanceTelemetryInitializer.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/TelemetryInitializers/DomainNameRoleInstanceTelemetryInitializerTests.cs
Fix Issue #671  .
Brought back DomainNameRoleInstanceTelemetryInitializer 
>  Bring back DomainNameRoleInstanceTelemetryInitializer to fix bug 671

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/ApplicationInsightsJavaScript.cs
- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs
- src/Microsoft.ApplicationInsights.AspNetCore/RequestTrackingTelemetryModule.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/RequestTrackingMiddlewareTest.cs
RequestTelemetry is not populated with HttpMethod which is obsolete. HttpMethod is already part of Name, so this information is redundant as well.
This makes asp.net core sdk in sync with web sdk.
Fix Issue #675 .
> RequestTelemetry is not populated with HttpMethod which is obsolete

- test/FunctionalTestUtils20/FunctionalTestUtils20.csproj
- test/FunctionalTestUtils20/HttpListenerObservableBase.cs
- test/FunctionalTestUtils20/InProcessServer.cs
- test/FunctionalTestUtils20/TelemetryHttpListenerObservable.cs
- test/FunctionalTestUtils20/TelemetryTestsBase.cs
- test/MVCFramework20.FunctionalTests/Startup.cs
- test/WebApi20.FunctionalTests/FunctionalTest/MultipleWebHostsTests.cs
..without which Xunit runner was throwing fatal exception.
2018-05-08T21:08:10.5709157Z [xUnit.net 00:00:00.2280923] Catastrophic failure: System.TypeLoadException: Could not load type 'System.Runtime.Remoting.Channels.IChannel' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Fix Issue # .
- Please follow [these] (https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/Readme.md) instructions to build and test …
> Change target framework for FunctionalTestUtils netcoreapp

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
AddAutoCollectedMetricExtractor  was always set to default (true) value, and user input was not respected. This fixes that, and modifies the unit test which should have caught this.
This issue manifested as FuncTest failures (random ones), when telemetry from AddAutoCollectedMetricExtractor  caused telemetry count to be incorrect. This fix should stabilize those func tests now.
- Please follow [these] (https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/Readme.md) instructions to build …
> Fixed a bug so that AddAutoCollectedMetricExtractor flag is respected

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
Partially Fix Issue #470 to enable perf counter in Azure Web Apps 
Updates version to 2.4.0-beta1
Updates web/base to 2.7.0-beta1
> Enable performance counter for asp.net core apps in Azure Web Apps

- src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj
Symbols packages had to be disabled due to a bug in our build infrastructure.
That bug has been resolved and we are re-enabling this.
> re-enable symbols packages

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/Common/StringUtilities.cs
- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs
- test/FunctionalTestUtils20/TelemetryTestsBase.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/RequestTrackingMiddlewareTest.cs
- test/WebApi20.FunctionalTests/FunctionalTest/RequestTelemetryWebApiTests.cs
See https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/952:
> We are going to gradually enable W3C support in ApplicaitonInsights.
> While the details and backward compatibility conditions are still not clear, we want to make sure that customers have enough time to transition to W3C format and this change is the first step in this transition.
> This change generates Activity RootId in the format of W3C traceId when there are no parents.
> I.e. if the service has received Request-Id (or legacy) header from upstream, it will use it, no matter which format it follows.
> However, if there were no such header in the incoming request, the new operation id will comply with W3C spec for traceId.
> This is a temporary workaround that could be removed once W3C supported in .NET …
> Generate W3C-compatible operation id if there is no request-id header

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptionsSetup.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
> Default TelemetryProcessors to be added on DefaultSink instead of on common pipeline

- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/HttpRequestExtensions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj
- src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/TelemetryInitializerBase.cs
Add the FxCop Analyzer to Non-Test projects.
This changed number an analyzer warnings from 304 to 320.
I fixed the 2 nameof() warnings.
New total 218
> add fxcop analyzer

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLogger.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Logging/ApplicationInsightsLoggerTests.cs
Fix Issue #754  .
Add ex.Data properties to exceptionTelemetry.Properties
> Log ex.Data as additional telemetry data

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsServiceOptions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/DependencyCollectionOptions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/RequestCollectionOptions.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
- test/WebApi20.FunctionalTests/FunctionalTest/RequestTelemetryWebApiTests.cs
Fix Issue https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/1120 on AspNetCore
We added localhost and 127.0.0.1 to the list of domains for which we don't inject correlation headers because of legacy (x-ms* headers). Injecting them into the request breaks Azure Storage SDK auth mechanism and causes errors on the emulator.
However, these headers are opt-in since AspNetCore SDK 2.4.0 (DepCollector 2.6.0) and we can safely add correlation headers on localhost.
This change removes localhost and 127.0.0.1 from the excluded list by default (if legacy headers are not on).
It also adds configuration to enable legacy headers and in this case excludes localhost and 127.0.0.1
If you want to to …
> Do not prevent correlation headers injection on localhost

- CHANGELOG.md
- NuGet.config
- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs
- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/IApplicationInsightDiagnosticListener.cs
- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/MvcDiagnosticsListener.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Extensibility/Implementation/Tracing/AspNetEventSource.cs
- src/Microsoft.ApplicationInsights.AspNetCore/RequestTrackingTelemetryModule.cs
- test/FunctionalTestUtils20/TelemetryTestsBase.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/ExceptionTrackingMiddlewareTest.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/RequestTrackingMiddlewareTest.cs
- test/WebApi20.FunctionalTests/FunctionalTest/MultipleWebHostsTests.cs
Fix Issue #621
ServiceFabric supports running multiple apps on the same host. Each app has its own AppInsights pipeline configured. i.e. there are multiple active dependency collectors and diagnostics listeners. Each of them receives even about dependency calls and tracks duplicates.
This change allows only one listener to be 'active': i.e. track telemetry.
When it is disposed, a new active listener is chosen between survivors.
See also https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/1013 which fixes the issue for dependencies.
If you want to to re-run the build/tests, the easiest way is to simply Close and Re-Open this same PR. (Just click 'close pull request' followed by 'open pull …
> Fix duplicated request telemetry when multiple hosts run in the same process

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLoggerFactoryExtensions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLoggerOptions.cs
Fix Issue #817.
ApplicationInsights Logger is now implemented in Microsoft.Extensions.Logging.ApplicationInsights nuget package.
Please install the new package and configure logging using `ApplicationInsightsLoggingBuilderExtensions.AddApplicationInsights` overloads.
See examples in https://github.com/Microsoft/ApplicationInsights-dotnet-logging/pull/239
> Deprecate ILogger extensions in favor of Microsoft.Extensions.Logging.ApplicationInsights package

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs
- src/Microsoft.ApplicationInsights.AspNetCore/RequestTrackingTelemetryModule.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/ExceptionTrackingMiddlewareTest.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/HostingDiagnosticListenerTest.cs
```
System.TypeInitializationException : The type initializer for 'Microsoft.ApplicationInsights.AspNetCore.DiagnosticListeners.HostingDiagnosticListener' threw an exception.
---- System.TypeLoadException : Method 'ConfigureAppConfiguration' in type 'Microsoft.AspNetCore.Hosting.WebHostBuilder' from assembly 'Microsoft.AspNetCore.Hosting, Version=1.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
at Microsoft.ApplicationInsights.AspNetCore.DiagnosticListeners.HostingDiagnosticListener.Dispose()
at Microsoft.ApplicationInsights.AspNetCore.RequestTrackingTelemetryModule.Dispose(Boolean disposing)
```
HostingDiagnosticListener uses WebHostBuilder class to determine Asp.NET Core version. Base IWebHostBuilder interface is loaded from …
> Fix TypeInitializationException for WebHostBuilder

- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptionsSetup.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/HostingDiagnosticListenerTest.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/HttpHeadersUtilitiesTest.cs
- test/WebApi20.FunctionalTests/FunctionalTest/TelemetryModuleWorkingWebApiTests.cs
W3C implementation is used by Web and AspNetCore SDKs.
We are going to enable W3C for some 1DS users that do not necessarily use Web SDK (and reference DependencyCollector that declares W3C implementation).
Without this change, we would require everyone to install base + dependency collector just to onboard W3C. With this change, it is still an explicit choice to enable it.
W3C is moved to base, Implementation in dependency collector is deprecated.
> Switch to W3C in base, and not in DependencyCollector

- .vsts/linux-build.yml
- CHANGELOG.md
- NugetAudit.ps1
- src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj
- Update version to 2.6.0
- Update base / web / other dependencies to 2.9.0
- LicenseUrl fix
> Prepare for 2.6.0 release and LicenseUrl update

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs
- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/IApplicationInsightDiagnosticListener.cs
- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/MvcDiagnosticsListener.cs
- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/PropertyFetcher.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/HttpRequestExtensions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj
- src/Microsoft.ApplicationInsights.AspNetCore/RequestTrackingTelemetryModule.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/TelemetryInitializers/OperationNameTelemetryInitializerTests.cs
Try out using DiagnosticListener without DiagnosticAdapter and see it it improves performance
> Remove DiagnosticAdapter and use DiagnosticListener directly

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HeadersUtilities.cs
- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs
- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HttpHeadersUtilities.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/HttpRequestExtensions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLogger.cs
- src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/AspNetCoreEnvironmentTelemetryInitializer.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/HeadersUtilitiesTest.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/HostingDiagnosticListenerTest.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/TelemetryInitializers/AspNetCoreEnvironmentTelemetryInitializerTests.cs
- Swtich from Diagnostics adapters to listeners from @lmolkova (was already merged into develop, this commit is therefore ignored by PR);
- Switch from `Initialize()` to `InitializeInsturmenationKey()` to prevent second round of Telemetry Initializers
- `GetUri` updates, 2x gain ([this bug](https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/862) is still an issue, though)
- `SetHeaderKeyValue` updates, 10x gain
- Use deprecated `Properties` for a while again to avoid second concurrent dictionary initialization for `GlobalProperties`.
- Test updates, including awesome contribution from @lmolkova to fix W3C correlation the aforementioned changes broke
> Performance fixes, wave 1.

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/RequestCollectionOptions.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
Fix Issue #861  .
Fixed by setting default value for `TrackExceptions` in `RequestCollectionOptions` to be false. User who disable ILogger (using filters), can get the exceptions from RequestTrackingModule, by modifying `TrackExceptions` in `RequestCollectionOptions`  to true, as shown below:
```csharp
public void ConfigureServices(IServiceCollection services)
{            
services.AddApplicationInsightsTelemetry();
services.ConfigureTelemetryModule<Microsoft.ApplicationInsights.AspNetCore.RequestTrackingTelemetryModule>((req, o) => req.CollectionOptions.TrackExceptions = true);
}
```
If you want to to re-run the build/tests, the easiest way is to simply Close and Re-Open this same PR. (Just click …
> Avoid duplicate exception from Request module and ILogger

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/IJavaScriptSnippet.cs
- src/Microsoft.ApplicationInsights.AspNetCore/JavaScriptSnippet.cs
Fix Issue #890 
Add `IJavaScriptSnippet` service interface and update the `IServiceCollection` extension to register it for `JavaScriptSnippet`.
Added the service registration alongside the original `services.AddSingleton<JavaScriptSnippet>()` to maintain backward compatibility.
> Add IJavaScriptSnippet

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/Implementation/ApplicationInsightsStartupFilter.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj
> 2.7.1 Hotfix

- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
This only changes a code comment and code indent. The comment about how to override the LogLevel in appsettings.json did not make it clear that the required keys must appear within `Logging` in appsettings.json.
Fix Issue # N/A.
<Short description of the fix.> N/A
> Improve slightly misleading comment for beginners

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/JavaScriptSnippet.cs
Fix Issue #502  .
This fix to make application insights work in web api apps in .netcore 3.0, as web encoders are not present in web api.
Once test infra has 3.0, need to add functional test to ensure apps dont crash if no encoder present.
> Make JavaScriptEncoder optional and Fallback to JavaScriptEncoder.Default

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs
- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/RequestResponseHeaders.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/HostingDiagnosticListenerTest.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Microsoft.ApplicationInsights.AspNetCore.Tests.csproj
Fix Issue #939  .
Also made minor improvements to unit tests as well.
> Remove x-ms based correlation.

- Schema/PublicSchema/ContextTagKeys.bond
- Schema/PublicSchema/MessageData.bond
- Schema/PublicSchema/RemoteDependencyData.bond
- Schema/PublicSchema/RequestData.bond
- test/ApplicationInsightsTypes/Generated/ContextTagKeys_types.cs
- test/ApplicationInsightsTypes/Generated/MessageData_types.cs
- test/ApplicationInsightsTypes/Generated/RemoteDependencyData_types.cs
- test/ApplicationInsightsTypes/Generated/RequestData_types.cs
Good people commented on my previous pool request after it was already completed that automated merge of my branch and develop overwrote some spelling fixes we already had in tests.
Restoring the right spelling back.
> Fix spelling after merge

- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/HostingDiagnosticListenerTest.cs
- test/TestApp30.Tests/BasicTestWithCorrelation.cs
- test/WebApi20.FunctionalTests/FunctionalTest/RequestCorrelationTests.cs
If Activity is recorded, we are going to sample in proactively (i.e. give more weight for these items, see https://github.com/Microsoft/ApplicationInsights-dotnet/pull/1200)
When we proactively sample features out, we should check Activity.Recorded first and only sample out those which are not recorded.
Also, I noticed parent -id on requests is not set correctly in W3C format. fixing that.
> Do not set sampledOut flag if activity is recorded and parentId fixes

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj
- test/EmptyApp.FunctionalTests/FunctionalTest/RequestTelemetryEmptyAppTests.cs
- test/EmptyApp.FunctionalTests/FunctionalTest/TelemetryModuleWorkingEmptyAppTests.cs
- test/EmptyApp20.FunctionalTests/FunctionalTest/RequestTelemetryEmptyAppTests.cs
- test/EmptyApp20.FunctionalTests/FunctionalTest/TelemetryModuleWorkingEmptyAppTests.cs
- test/MVCFramework.FunctionalTests/FunctionalTest/RequestTelemetryMvcTests.cs
- test/MVCFramework.FunctionalTests/FunctionalTest/TelemetryModuleWorkingMvcTests.cs
- test/MVCFramework20.FunctionalTests/FunctionalTest/RequestTelemetryMvcTests.cs
- test/MVCFramework20.FunctionalTests/FunctionalTest/TelemetryModuleWorkingMvcTests.cs
- test/WebApi.FunctionalTests/FunctionalTest/TelemetryModuleWorkingWebApiTests.cs
- test/WebApi20.FunctionalTests/FunctionalTest/MultipleWebHostsTests.cs
- test/WebApi20.FunctionalTests/FunctionalTest/RequestDependencyCorrelationTests.cs
also updated DiagnosticSource to stay in sync with WebSDK https://github.com/microsoft/ApplicationInsights-dotnet-server/pull/1252
> bump version 2.8.0-beta3

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj
- src/Microsoft.ApplicationInsights.WorkerService/Microsoft.ApplicationInsights.WorkerService.csproj
This is to create clarity around our version numbers. We are now in the "2.12 milestone"
> skip version to v2.12

- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
- src/Microsoft.ApplicationInsights.WorkerService/ApplicationInsightsExtensions.cs
- src/Shared/Extensions/ApplicationInsightsExtensions.cs
- src/Shared/Extensions/ApplicationInsightsServiceOptions.cs
I'm adding new properties to ApplicationInsightsServiceOptions to support ConnecitonStrings
I need to make sure I support all the use cases (I found one of the copies but didn't immediately find the second).
This POCO should be able to manage it's own copy properties.
This will also help future devs who add a new property to also add to this method.
> refactor ApplicationInsightsServiceOptions

- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs
- src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HttpHeadersUtilities.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Extensibility/Implementation/Tracing/AspNetCoreEventSource.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Implementation/AspNetCoreMajorVersion.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLoggerFactoryExtensions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Properties/AssemblyInfo.cs
- src/Microsoft.ApplicationInsights.AspNetCore/SdkVersionUtils.cs
- src/Microsoft.ApplicationInsights.WorkerService/Implementation/Tracing/WorkerServiceEventSource.cs
- src/Microsoft.ApplicationInsights.WorkerService/Properties/AssemblyInfo.cs
- src/Shared/Extensions/ApplicationInsightsExtensions.cs
- src/Shared/Implementation/ITelemetryModuleConfigurator.cs
- src/Shared/Implementation/TelemetryConfigurationOptionsSetup.cs
- src/Shared/Internals/ApplicationNameProvider.cs
- src/Shared/Shared.projitems
- src/Shared/TelemetryInitializers/ComponentVersionTelemetryInitializer.cs
This is a prerequisite to requiring FxCop on check-ins.
**Warnings Count**
-  before 299
- after 111 (only counting product code, 189 including tests)
**Changes**
- no functional changes
- fix whitespace.
- fix usings
- include missing xml documentation.
- disable file header rule
> fix fxcop warnings

- CHANGELOG.md
- src/Microsoft.ApplicationInsights.AspNetCore/Extensibility/Implementation/Tracing/AspNetCoreEventSource.cs
- src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
- src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/AzureAppServiceRoleNameFromHostNameHeaderInitializer.cs
- src/Microsoft.ApplicationInsights.WorkerService/ApplicationInsightsExtensions.cs
- src/Shared/Extensions/ApplicationInsightsExtensions.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Microsoft.ApplicationInsights.AspNetCore.Tests.csproj
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/TelemetryInitializers/AzureAppServiceRoleNameFromHostNameHeaderInitializerTests.cs
Fix Issue # https://github.com/microsoft/ApplicationInsights-dotnet-server/issues/1207
There'll be similar fix for Asp.Net Apps in https://github.com/microsoft/ApplicationInsights-dotnet-server repo as well.
> Add new RoleName initializer for Azure Web App to accurately reflect slot swaps

- Directory.Build.props
- Nupkg.props
- Product.props
- Signing.props
- src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj
- src/Microsoft.ApplicationInsights.WorkerService/Microsoft.ApplicationInsights.WorkerService.csproj
- test/ApplicationInsightsTypes/ApplicationInsightsTypes.csproj
- test/EmptyApp.FunctionalTests/EmptyApp.FunctionalTests10.csproj
- test/EmptyApp20.FunctionalTests/EmptyApp20.FunctionalTests20.csproj
- test/FunctionalTestUtils/FunctionalTestUtils.csproj
- test/FunctionalTestUtils20/FunctionalTestUtils20.csproj
- test/MVCFramework.FunctionalTests/MVCFramework.FunctionalTests10.csproj
- test/MVCFramework20.FunctionalTests/MVCFramework20.FunctionalTests20.csproj
- test/Microsoft.ApplicationInsights.AspNetCore.Tests/Microsoft.ApplicationInsights.AspNetCore.Tests.csproj
- test/Microsoft.ApplicationInsights.WorkerService.Tests/Microsoft.ApplicationInsights.WorkerService.Tests.csproj
- test/TestApp30.Tests/TestApp30.Tests30.csproj
- test/TestApp30/TestApp30.csproj
- test/WebApi.FunctionalTests/WebApi.FunctionalTests10.csproj
- test/WebApi20.FunctionalTests/WebApi20.FunctionalTests20.csproj
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1214
1. Reorganize individual repos. This is to ensure that there are no conflicting directories or file names and to guarantee no conflicts when migrating source. This will require some minor changes to existing build definitions.
**Changes**
remove "artifacts" directory.
Now using same bin and obj directories as all other repos.
> refactor projects
