microsoft/ApplicationInsights-aspnetcore

src/Microsoft.ApplicationInsights.AspNet/ApplicationInsightsExceptionMiddleware.cs
src/Microsoft.ApplicationInsights.AspNet/ExceptionTrackingMiddleware.cs
src/Microsoft.ApplicationInsights.AspNet/Fakes.cs
test/Microsoft.ApplicationInsights.AspNet.Tests/ApplicationInsightsExceptionMiddlewareTest.cs
test/Microsoft.ApplicationInsights.AspNet.Tests/FakeTelemetryChannel.cs

Change exception tracking to report it as HandledAt = Platform

---

Readme.md

Remove getting started and inserted link to the wiki instead.
cc: @alancameronwills

edit readme.md - remove getting started and add release notes

---

src/Microsoft.ApplicationInsights.AspNet/ApplicationInsightsJavaScript.cs
src/Microsoft.ApplicationInsights.AspNet/Extensions/ApplicationInsightsExtensions.cs
src/Microsoft.ApplicationInsights.AspNet/Extensions/ApplicationInsightsJavaScriptExtensions.cs
src/Microsoft.ApplicationInsights.AspNet/JavaScript/IApplicationInsightsJavaScript.cs
test/Microsoft.ApplicationInsights.AspNet.Tests/JavaScript/ApplicationInsightsJavaScriptTest.cs
test/Mvc6Framework45.FunctionalTests/Views/Shared/_Layout.cshtml

Addressing @Eilon feedback on integration points

use htmlhelpter in cshtml

---

NuGet.config
Readme.md
src/Microsoft.ApplicationInsights.AspNet/project.json

rename vNext and v5 to ASP.NET 5

---

src/Microsoft.ApplicationInsights.AspNet/project.json

use Interfaces references instead of real pakages

---

src/Microsoft.ApplicationInsights.AspNet/project.json
test/FunctionalTestUtils/project.json
test/Microsoft.ApplicationInsights.AspNet.Tests/project.json
test/Mvc6Framework45.FunctionalTests/project.json

move to 1.1 Application Insights SDK

---

test/Mvc6Framework45.FunctionalTests/project.json

Update EF package name

---

test/Mvc6Framework45.FunctionalTests/project.json

See https://github.com/aspnet/Announcements/issues/42 for details

revert EF package names

---

src/Microsoft.ApplicationInsights.AspNet/ApplicationInsightsJavaScript.cs

In response to this comment: https://github.com/Microsoft/ApplicationInsights-aspnet5/issues/101

use type instead of language in javascript snippet

---

src/Microsoft.ApplicationInsights.AspNet/SdkVersionUtils.cs
src/Microsoft.ApplicationInsights.AspNet/TelemetryInitializers/OperationNameTelemetryInitializer.cs
test/Mvc6Framework45.FunctionalTests/Migrations/ApplicationDbContextModelSnapshot.cs
test/Mvc6Framework45.FunctionalTests/Models/IdentityModels.cs
test/WebApiShimFw46.FunctionalTests/Startup.cs

- React to changes in ef & mvc.
- Address previous PR's feedback.
- Update SDKVersion to 1.0.0-beta7

React to changes in ef & mvc

---

src/Microsoft.ApplicationInsights.AspNet/TelemetryInitializers/WebUserTelemetryInitializer.cs
test/Microsoft.ApplicationInsights.AspNet.Tests/TelemetryInitializers/WebUserTelemetryInitializerTests.cs

Fix for #138 
CC: @abaranch, @kartang

Remove UserAcquisitionDate

---

src/Microsoft.ApplicationInsights.AspNet/Extensions/ApplicationInsightsExtensions.cs
test/EmptyApp.FunctionalTests/Startup.cs
test/Microsoft.ApplicationInsights.AspNet.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
test/Mvc6Framework45.FunctionalTests/Startup.cs
test/WebApiShimFw46.FunctionalTests/Startup.cs

Added backwards compatibility for creating TelemetryClient without using dependency injection.

Added backwards compatibility for creating TelemetryClient without using dependency injection.

---

NuGet.config
src/Microsoft.ApplicationInsights.AspNetCore/project.json
test/EmptyApp.FunctionalTests/FunctionalTest/ExceptionTelemetryEmptyAppTests.cs
test/EmptyApp.FunctionalTests/project.json
test/FunctionalTestUtils/InProcessServer.cs
test/FunctionalTestUtils/project.json
test/MVCFramework45.FunctionalTests/FunctionalTest/ExceptionTelemetryMvcTests.cs
test/MVCFramework45.FunctionalTests/Startup.cs
test/MVCFramework45.FunctionalTests/project.json
test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
test/Microsoft.ApplicationInsights.AspNetCore.Tests/project.json
test/WebApiShimFw46.FunctionalTests/FunctionalTest/TelemetryModuleWorkingWebApiTests.cs
test/WebApiShimFw46.FunctionalTests/Startup.cs
test/WebApiShimFw46.FunctionalTests/project.json

- Adding full framework setup to the functional tests

Aligning with the changes from aspnet

---

NuGet.config
Signing.props
dirs.proj
test/EmptyApp.FunctionalTests/project.json
test/FunctionalTestUtils/project.json
test/MVCFramework45.FunctionalTests/project.json
test/Microsoft.ApplicationInsights.AspNetCore.Tests/project.json
test/WebApiShimFw46.FunctionalTests/project.json

Added test projects and additional debugging messages.
Resolved xunit reference problems.

Made signing check for the existence of the signing DLL.

---

src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/ClientIpHeaderTelemetryInitializer.cs
src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/OperationNameTelemetryInitializer.cs
src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/TelemetryInitializerBase.cs
test/Microsoft.ApplicationInsights.AspNetCore.Tests/Helpers/HttpContextAccessorHelper.cs
test/Microsoft.ApplicationInsights.AspNetCore.Tests/Helpers/HttpContextStub.cs
test/Microsoft.ApplicationInsights.AspNetCore.Tests/Helpers/HttpRequestStub.cs
test/Microsoft.ApplicationInsights.AspNetCore.Tests/TelemetryInitializers/ClientIpHeaderTelemetryInitializerTests.cs

Fix NullRef in ClientIpTelemetryInitializer

---

src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/CorrelationIdLookupHelper.cs

Prevent exception thrown when baseAddress is not set in the configuration.
@dnduffy,
There is still one missing piece that I couldn't figure out but this commit should fix the functional test of TestBasicDependencyPropertiesAfterRequestingBasicPage for .NET 451:
Running result:
xUnit.net .NET CLI test runner (64-bit **Desktop .NET win10-x64**)
Discovering: WebApiShimFw46.FunctionalTests
Discovered:  WebApiShimFw46.FunctionalTests
Starting:    WebApiShimFw46.FunctionalTests
Finished:    WebApiShimFw46.FunctionalTests
=== TEST EXECUTION SUMMARY ===
WebApiShimFw46.FunctionalTests  Total: 7, **Errors: 0**, **Failed: 0**, Skipped: 0, Time: 4.817s
SUMMARY: Total: 2 targets, Passed: 2, Failed: 0.

Protect CorrelationIdLookupHelper for empty base address

---

src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/CorrelationIdLookupHelper.cs
test/Microsoft.ApplicationInsights.AspNetCore.Tests/CorrelationIdLookupHelperTest.cs
test/Microsoft.ApplicationInsights.AspNetCore.Tests/FakeTelemetryChannel.cs

Add unit tests to cover basic scernarios for correlationidlookuphelper

---

.gitignore
src/Microsoft.ApplicationInsights.AspNetCore/Extensibility/Implementation/Tracing/AspNetEventSource.cs
test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensibility/Implementation/Tracing/EventSourceTests.cs

https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/410

Fixes issue 410 - Remove the use of Platform Abstractions

---

test/MVCFramework45.FunctionalTests/FunctionalTest/RequestTelemetryMvcTests.cs

I found the last one, the tests pass now.

Removed an ifdef for NET451 that is no longer needed.

---

test/FunctionalTestUtils20/TelemetryTestsBase.cs

Minor change to begin hunting down all rca for random test failures in lab machines.
This simply adds some basic traces.

Added few traces to help test failure investigations.

---

CHANGELOG.md
src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptionsSetup.cs
src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj

Addresses the issue https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/216

Adding support for Live Metrics in .NET Core

---

src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs

See https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/740, https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/735

Enable ServiceBus diagnostic source

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
Readme.md

PR created again to test CI build triggers

GH items added.

---

src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj

Bump version

---

src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs

Fix issue Microsoft/ApplicationInsights-dotnet-server#753.

[DS] Enable EventHubs diagnostic source

---

Signing.props

Update signing plugin version

---

CHANGELOG.md
Signing.props
src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj

Fix issue # .
1. Update signing plugin version
2. Modified symbols to be full, instead of portable to help in indexing.
3. Update changelog.

Beta3 release

---

src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs
src/Microsoft.ApplicationInsights.AspNetCore/Extensions/DefaultApplicationInsightsServiceConfigureOptions.cs
src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLogger.cs

String formatting made culture neutral for compliance.

---

CHANGELOG.md
src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj

Update base and web sdk references
Fix Issue # .

2.5 stable release.

---

Signing.props

Signing version update

---

Signing.props

dev to master

---

CHANGELOG.md
src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj

2.5.1 of base and web

---

CHANGELOG.md
src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj

Dev to master for 2.5.1 release

---

src/Microsoft.ApplicationInsights.AspNetCore/ApplicationInsightsJavaScript.cs

Check httpcontext for null in javascript snippet. Fix issue 556

---

Signing.props

Update signing plugin

---

CHANGELOG.md
src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj

Update System.Net.Http to version 4.3.2

---

CHANGELOG.md
src/Microsoft.ApplicationInsights.AspNetCore/Extensions/HttpRequestExtensions.cs
src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj

Updated base and web to latest stable 2.6.1
Also a small change to merged PR
https://github.com/Microsoft/ApplicationInsights-aspnetcore/pull/677/files

2.6.0 stable

---

Signing.props

Update microbuild signing plugin version

---

CHANGELOG.md
src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj

Update base/web to 2.6.4

---

CHANGELOG.md
src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj
test/FunctionalTestUtils/BackTelemetryChannel.cs

Update base and web to 27beta2, bump version to 2.4. beta2

---

test/Microsoft.ApplicationInsights.AspNetCore.Tests/RequestTrackingMiddlewareTest.cs

Attempt to fix some rare and random test failures: https://mseng.visualstudio.com/AppInsights/AppInsights%20Team/_build/results?buildId=6771326&view=ms.vss-test-web.test-result-details

Cleanup after requests collection tests

---

CHANGELOG.md
src/Microsoft.ApplicationInsights.AspNetCore/Common/StringUtilities.cs
src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs
src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj
test/FunctionalTestUtils20/TelemetryTestsBase.cs
test/Microsoft.ApplicationInsights.AspNetCore.Tests/RequestTrackingMiddlewareTest.cs
test/WebApi20.FunctionalTests/FunctionalTest/RequestTelemetryWebApiTests.cs

Dev to master for 2.4.0-beta4

---

src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj

Bump version to beta4

---

CHANGELOG.md
src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj

Update to 2.4.0 stable

---

CHANGELOG.md
src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj

2.7.1 of base and web

---

CHANGELOG.md
src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj

Update base web to 2.7.2

---

src/Microsoft.ApplicationInsights.AspNetCore/ITelemetryProcessorFactory.cs
src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLogger.cs
src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/AspNetCoreEnvironmentTelemetryInitializer.cs
test/Microsoft.ApplicationInsights.AspNetCore.Tests/TelemetryInitializers/AspNetCoreEnvironmentTelemetryInitializerTests.cs

Fix warnings about obsolete fields

---

src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj

added azure tag to nuget tags for discoverability

---

NugetAudit.ps1

- add script to audit nupkg during build
-  update nuget.exe to 4.7 required to verify signing

add script to audit nupkg during build.

---

CHANGELOG.md
src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj

Bump to next beta, update latest beta of base and web

---

CHANGELOG.md
src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj

dev to master for 2.6.0-beta1

---

src/Microsoft.ApplicationInsights.AspNetCore/Extensions/DefaultApplicationInsightsServiceConfigureOptions.cs

Fix comment typo

---

CHANGELOG.md
src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj
test/EmptyApp20.FunctionalTests/Startup.cs
test/MVCFramework20.FunctionalTests/Startup.cs
test/WebApi20.FunctionalTests/Startup.cs

Bump to 2.7.0-beta2

---

src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj

bump to 2.7.0-beta3

---

src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs

Encloses 2 property names in double quotes

Add missing double quotes in JSON snippet

---

src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/ContextData.cs
src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HeadersUtilities.cs
src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs
src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/MvcDiagnosticsListener.cs
src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/PropertyFetcher.cs
src/Microsoft.ApplicationInsights.AspNetCore/ExceptionTrackingMiddleware.cs
src/Microsoft.ApplicationInsights.AspNetCore/Extensibility/Implementation/Tracing/AspNetCoreEventSource.cs
src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsServiceOptions.cs
src/Microsoft.ApplicationInsights.AspNetCore/Extensions/DefaultApplicationInsightsServiceConfigureOptions.cs
src/Microsoft.ApplicationInsights.AspNetCore/Extensions/HttpRequestExtensions.cs
src/Microsoft.ApplicationInsights.AspNetCore/ITelemetryModuleConfigurator.cs
src/Microsoft.ApplicationInsights.AspNetCore/Implementation/ApplicationInsightsStartupFilter.cs
src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptionsSetup.cs
src/Microsoft.ApplicationInsights.AspNetCore/JavaScriptSnippet.cs
src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLogger.cs
src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLoggerFactoryExtensions.cs
src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLoggerOptions.cs
src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLoggerProvider.cs
src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj
src/Microsoft.ApplicationInsights.AspNetCore/RequestTrackingTelemetryModule.cs
src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/AspNetCoreEnvironmentTelemetryInitializer.cs
src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/DomainNameRoleInstanceTelemetryInitializer.cs
src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/TelemetryInitializerBase.cs
src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/WebSessionTelemetryInitializer.cs
src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/WebUserTelemetryInitializer.cs

FIx Code analyzer warnings

---

src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/ContextData.cs
src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs
src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HttpHeadersUtilities.cs
src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/MvcDiagnosticsListener.cs
src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/PropertyFetcher.cs
src/Microsoft.ApplicationInsights.AspNetCore/Extensibility/Implementation/Tracing/AspNetCoreEventSource.cs
src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsWebHostBuilderExtensions.cs
src/Microsoft.ApplicationInsights.AspNetCore/Extensions/HttpRequestExtensions.cs
src/Microsoft.ApplicationInsights.AspNetCore/Extensions/RequestCollectionOptions.cs
src/Microsoft.ApplicationInsights.AspNetCore/ITelemetryModuleConfigurator.cs
src/Microsoft.ApplicationInsights.AspNetCore/Implementation/ApplicationInsightsStartupFilter.cs
src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptionsSetup.cs
src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryModuleConfigurator.cs
src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLogger.cs
src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLoggerFactoryExtensions.cs
src/Microsoft.ApplicationInsights.AspNetCore/Properties/AssemblyInfo.cs
src/Microsoft.ApplicationInsights.AspNetCore/RequestTrackingTelemetryModule.cs
src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/AspNetCoreEnvironmentTelemetryInitializer.cs
src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/ClientIpHeaderTelemetryInitializer.cs
src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/DomainNameRoleInstanceTelemetryInitializer.cs
src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/WebSessionTelemetryInitializer.cs
src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/WebUserTelemetryInitializer.cs

another round of analyzer fixed

---

src/Microsoft.ApplicationInsights.AspNetCore/ExceptionTrackingMiddleware.cs
src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
src/Microsoft.ApplicationInsights.AspNetCore/RequestTrackingTelemetryModule.cs
src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/AspNetCoreEnvironmentTelemetryInitializer.cs
src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/ClientIpHeaderTelemetryInitializer.cs
src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/ComponentVersionTelemetryInitializer.cs
src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/OperationNameTelemetryInitializer.cs
src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/SyntheticTelemetryInitializer.cs
src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/TelemetryInitializerBase.cs
src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/WebSessionTelemetryInitializer.cs
src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/WebUserTelemetryInitializer.cs

@cijothomas, if you're okay with this go ahead and SquashMerge. :)

fxcop: update xml comments

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
Readme.md

minor wordings change in github templates and readme etc.

---

src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj

MicroBuild in the conditional ItemGroup has been causing problems.
Changing all projects for consistency.

fix signing

---

src/Microsoft.ApplicationInsights.AspNetCore/Implementation/ApplicationInsightsStartupFilter.cs

- This will end up in application logs instead of logging solely into the event source
cc @cijothomas

Log ApplicationInsightsStartupFilter exceptions

---

src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj

- refactor nupkg properties.
- moved properties into two sections; project specific and generic. I intend to remove generic in favor of the nupkg.props file
- Add SymbolPackageFormat = snupkg.
https://github.com/microsoft/ApplicationInsights-Home/issues/370

new symbols format and refactor nupkg properties

---

CHANGELOG.md
src/Microsoft.ApplicationInsights.AspNetCore/Extensions/HttpRequestExtensions.cs
test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/HttpRequestExtensionsTest.cs

Multiple hosts fix

---

CHANGELOG.md
src/Microsoft.ApplicationInsights.AspNetCore/Extensibility/Implementation/Tracing/AspNetCoreEventSource.cs
src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
src/Microsoft.ApplicationInsights.AspNetCore/Implementation/ApplicationInsightsStartupFilter.cs
src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptionsSetup.cs
test/Microsoft.ApplicationInsights.AspNetCore.Tests/HostingDiagnosticListenerTest.cs

LogLevel changed to Error and stack trace added for generic unknown exception within SDK

---

CHANGELOG.md
src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs

Correct name for Asp.Net Core eventcounters. added link to original source of EvenCounter

---

CHANGELOG.md
src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs
src/Microsoft.ApplicationInsights.AspNetCore/Extensibility/Implementation/Tracing/AspNetCoreEventSource.cs
src/Microsoft.ApplicationInsights.AspNetCore/Extensions/RequestCollectionOptions.cs
src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptionsSetup.cs
src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj
src/Microsoft.ApplicationInsights.AspNetCore/RequestTrackingTelemetryModule.cs
test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
test/Microsoft.ApplicationInsights.AspNetCore.Tests/Helpers/CommonMocks.cs
test/Microsoft.ApplicationInsights.AspNetCore.Tests/HostingDiagnosticListenerTest.cs
test/WebApi20.FunctionalTests/FunctionalTest/RequestCorrelationTests.cs

Read Correlation context always, update to beta2 of base

---

src/Shared/Extensions/ApplicationInsightsExtensions.cs

cleaning up this method.
I'm about to add a new setting here for ConnectionStrings and I want to keep this method concise.

refactor Extensions.AddTelemetryConfiguration

---

CHANGELOG.md
src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs
src/Microsoft.ApplicationInsights.WorkerService/ApplicationInsightsExtensions.cs
src/Shared/Extensions/ApplicationInsightsExtensions.cs
src/Shared/Extensions/ApplicationInsightsServiceOptions.cs
src/Shared/Implementation/NoOpTelemetryModule.cs
src/Shared/Shared.projitems
test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests.cs
test/WebApi20.FunctionalTests/FunctionalTest/RequestCorrelationTests.cs

Provide easy way to turnoff built-in modules, and an ikey read fix.

---

src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj
src/Microsoft.ApplicationInsights.WorkerService/Microsoft.ApplicationInsights.WorkerService.csproj

this is needed to test connection strings

bump version 2.12.0-beta1-build5020

---

CHANGELOG.md
src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj
src/Microsoft.ApplicationInsights.WorkerService/Microsoft.ApplicationInsights.WorkerService.csproj

Bump to 2.8.2

---

CHANGELOG.md
src/Microsoft.ApplicationInsights.AspNetCore/Microsoft.ApplicationInsights.AspNetCore.csproj
src/Microsoft.ApplicationInsights.WorkerService/Microsoft.ApplicationInsights.WorkerService.csproj

Bump to next beta1
